services:
  db:
    image: postgres:15
    container_name: wallet_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  test_db:
    image: postgres:15
    container_name: wallet_test_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
    # Внутри Docker-сети порт 5432, наружу не публикуем
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TEST_DB_USER} -d ${TEST_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    tmpfs:
      - /var/lib/postgresql/data

  app:
    build: .
    container_name: wallet_app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

  tests:
    build: .
    container_name: wallet_tests
    depends_on:
      test_db:
        condition: service_healthy
    env_file:
      - .env
    environment:
            - TEST_DATABASE_URL=postgresql+asyncpg://${TEST_DB_USER}:${TEST_DB_PASSWORD}@${TEST_DB_HOST}:${TEST_DB_PORT}/${TEST_DB_NAME}
    volumes:
      - .:/app
    command: >
      sh -c "
        echo 'Ожидание тестовой базы данных...' &&
        sleep 10 &&
        echo 'Проверка подключения к БД...' &&
        python check_db.py &&
        echo 'Запуск тестов...' &&
        python -m pytest tests/ -v --asyncio-mode=auto --tb=short
      "

volumes:
  postgres_data: